### ISSUE TITLE
Analysis of dividends and positions

### ISSUE THREAD

**Issue by sebanger** [keisentraut/python-comdirect-api#5]
I would like to discuss what are your ideas of the analysis part. So far I come up with the following ideas:
- key measures (Ranking, Total dividends, Actual performance (total and per year/month), DSR, PAR)
- portfolio plots via seaborn or plotly (interactive) or interactive web application of portfolio via bokeh or Gleam
- Including more or less up to date real stock data for performance measurement

Examples of common plots:
![Income heroes](https://user-images.githubusercontent.com/39982567/75538794-7f05f300-5a19-11ea-9f2c-8c45ef40f3af.png)
![diversifikation](https://user-images.githubusercontent.com/39982567/75539250-3b5fb900-5a1a-11ea-93e0-673327a5ed52.png)
![portfolio](https://user-images.githubusercontent.com/39982567/75539786-1d468880-5a1b-11ea-948c-0ad277fbe839.png)

**Comment by keisentraut** [comment]
I'm not sure, if I will implement this in the near future. This sounds like a lot of work and there are quite a lot much more advanced projects for this. An example is [Portfolio Performance](https://www.portfolio-performance.info/). Also, those charts are not very interesting for my boring personal "Three ETF" depot :)

However, in order to import your data from comdirect into your favorite tool, you need to get your data and this is where I see this project coming in handy.

So the first goal is to finish the API, the next one to write some scripts which can download your documents and your transactions as CSV.  If I get there and still am not bored by this little project, then I might think about this again... 

Obviously pull requests are welcome  :)

**Comment by sebanger** [comment]
No problem. This is one of my personal TODOs so I can be in charge of that. I also think that others are interested in those kind of analysis/portfolio performances. 
Yes, I know this tool but you have to insert your data by yourself. Furthermore, the charts are not very nice or too complex.

**Comment by TimsDevCorner** [comment]
@sebanger have you tried to import your data in such tools?

You can import your data in [Portfolie Performance](https://www.portfolio-performance.info/), as described [here](https://forum.portfolio-performance.info/t/import-csv-file/17123)

**Comment by sebanger** [comment]
I've imported my data into PowerBI. There I made all visualizations. It was very easy.
